library(tseries)
Log.return_x<-na.omit(ts(resampled_data['Log.return_x'], start=c(1948, 1), end=c(2020, 1), frequency=12))
adf.test(Log.return_x)
Log.return_y<-na.omit(ts(resampled_data['Log.return_y'], start=c(1948, 1), end=c(2020, 1), frequency=12))
adf.test(Log.return_y)
Log.return_x.1<-na.omit(ts(resampled_data['Log.return_x.1'], start=c(1948, 1), end=c(2020, 1), frequency=12))
adf.test(Log.return_x.1)
Log.return_y.1<-na.omit(ts(resampled_data['Log.return_y.1'], start=c(1948, 1), end=c(2020, 1), frequency=12))
adf.test(Log.return_y.1)
